- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars: 
     app: "wordpress"

- block:
  - name: Create backup directory
    shell: |
       mkdir -p /data/apps/wordpress/data/backup/plugin
       mkdir -p /data/apps/wordpress/data/backup/theme
  - name: Copy wp-cli
    copy:
      src: wp-cli.phar
      dest: /data/apps/wordpress/data/backup/wp-cli.phar
  
- block:
  - name: Download {{wordpress_solution}} theme to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{wordpress_theme_meta[wordpress_solution].theme}}.zip"
      dest: /data/apps/wordpress/data/backup/theme/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes

  - name: Download plugin to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{item}}.zip"
      dest: /data/apps/wordpress/data/backup/plugin/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes
    with_items:
      - "{{wordpress_theme_meta[wordpress_solution].plugin}}"
    when: wordpress_theme_meta[wordpress_solution].plugin !=""
    
  - name: Install theme and plugins
    shell: |
      echo "cp /data/apps/wordpress/data/backup/plugin/* /data/apps/wordpress/data/wordpress/wp-content/plugin" >> /data/apps/{{appname}}/src/after_up.sh
      echo "cp /data/apps/wordpress/data/backup/theme/* /data/apps/wordpress/data/wordpress/wp-content/theme" >> /data/apps/{{appname}}/src/after_up.sh
      echo "sudo sed -i 's/twentytwentytwo/{{wordpress_solution}}/g' /data/apps/wordpress/data/wordpress/wp-includes/default-constants.php" >> /data/apps/{{appname}}/src/after_up.sh
      echo "docker restart wordpress" >> /data/apps/{{appname}}/src/after_up.sh
      
  when: wordpress_solution != "" and wordpress_solution != "multisite"

- name: Set the multisite solution(TODO)
  shell:
    echo "add line [define( 'WP_ALLOW_MULTISITE', true );] to wp-config.php" >> /data/apps/{{appname}}/src/after_up.sh
  when: wordpress_solution == "multisite"
