- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars: 
     app: "wordpress"

- block:
  - name: Create backup directory
    shell: |
       mkdir -p /data/apps/wordpress/data/backup/plugins
       mkdir -p /data/apps/wordpress/data/backup/themes
  - name: Download wp-cli
    shell: |
      cd /data/apps/wordpress/data/backup
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      chmod +x wp-cli.phar
      mv wp-cli.phar wp
