- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars: 
     app: "wordpress"

- block:
  - name: Create backup directory
    shell: |
      mkdir -p /data/apps/wordpress/data/backup
  - name: Copy wp-cli
    copy:
      src: wp-cli.phar
      dest: /data/apps/wordpress/data/backup/wp-cli.phar

  - name: Add Install wp-cli for init
    shell: |
      echo "docker cp wp-cli.phar wordpress:/tmp"  >> /data/apps/{{appname}}/src/after_up.sh 
      echo "docker exec -it wordpress chmod +x /tmp/wp-cli.phar" >> /data/apps/{{appname}}/src/after_up.sh
      echo "docker exec -it wordpress mv /tmp/wp-cli.phar /usr/local/bin/wp" >> /data/apps/{{appname}}/src/after_up.sh
  
- block:
  - name: Download {{wordpress_solution}} theme to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{wordpress_theme_meta[wordpress_solution].theme}}.zip"
      dest: /data/apps/wordpress/data/backup/theme/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes

  - name: Download plugin to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{item}}.zip"
      dest: /data/apps/wordpress/data/backup/plugin/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes
    with_items:
      - "{{wordpress_theme_meta[wordpress_solution].plugin}}"
    when: wordpress_theme_meta[wordpress_solution].plugin !=""

  - name: Template default-constants.php
    template:
      src: default-constants.php
      dest: /data/apps/wordpress/data/backup
      owner: www-data
      group: www-data

  - name: Add tasks to init
    shell:
      echo "docker cp theme" >> /data/apps/{{appname}}/src/after_up.sh
      echo "docker cp plugins" >> /data/apps/{{appname}}/src/after_up.sh
      echo "docker cp default-constants.php" >> /data/apps/{{appname}}/src/after_up.sh

  when: wordpress_solution != ""
