- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars: 
     app: "wordpress"

- block:
  - name: Create backup directory
    shell: |
      mkdir -p /data/apps/wordpress/data/backup
  - name: Copy wp-cli
    copy:
      src: wp-cli.phar
      dest: /data/apps/wordpress/data/backup/wp-cli.phar
  
- block:
  - name: Download {{wordpress_solution}} theme to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{wordpress_theme_meta[wordpress_solution].theme}}.zip"
      dest: /data/apps/wordpress/data/backup/theme/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes

  - name: Download plugin to host machine
    unarchive:
      src: "{{wordpress_theme_download_url}}/{{wordpress_solution}}/{{item}}.zip"
      dest: /data/apps/wordpress/data/backup/plugin/{{wordpress_solution}}
      owner: www-data
      group: www-data
      remote_src: yes
    with_items:
      - "{{wordpress_theme_meta[wordpress_solution].plugin}}"
    when: wordpress_theme_meta[wordpress_solution].plugin !=""
  when: wordpress_solution != ""
