version: "3.8"

services:
  appmanage:
    image: websoft9dev/appmanage:${APP_VERSION}
    container_name: ${APP_NAME}
    pid: host
    privileged: true
    restart: unless-stopped
    volumes:
      - appmanage-logs:/usr/src/app/logs
      - appmanage-db:/usr/src/app/db
      - appmanage-config:/usr/src/app/config
    entrypoint: bash -c "/cmd.sh"
    ports:
      - ${APP_HTTP_PORT}:5000

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  appmanage-logs:
  appmanage-db:
