- pause:
    prompt: |
      Choice MySQL version: 
      0: MySQL8.0
      1: MySQL5.7
      private: no
      Default:0
  register: version_options

- set_fact:
    mysql_version_meta:
      "0": "8.0"
      "1": "5.7"
      
- set_fact:
    mysql_version: "{{mysql_version_meta[version_options.user_input]}}"

- debug:
    msg: "mysql_version is {{mysql_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_VERSION=.*/APP_VERSION={{mysql_version}}/g' {{installpath}}/{{appname}}/.env
