version: '3.8'

services:

  appmanage:
    image: appmanage:0.8
    container_name: appmanage
    restart: unless-stopped
    volumes:
      - /data:/data
    ports:
     - 5000:5000

networks:
  default:
    name: websoft9
    external: true
