version: '3.8'

services:

  appmanage:
    image: websoft9dev/appmanage:dev
    container_name: appmanage
    pid: host
    privileged: true
    restart: unless-stopped
    volumes:
      - logs:/usr/src/app/logs
    ports:
     - 5000:5000

networks:
  default:
    name: websoft9
    external: true

volumes:
  logs:
