- pause:
    prompt: |
      Choice MongoDB version: 
      0: MongoDB5.0
      1: MongoDB4.4
      2: MongoDB4.2
      private: no
      Default:0
  register: mongodb_version_options

- set_fact:
    mongodb_version_meta:
      "0": "5.0"
      "1": "4.4"
      "2": "4.2"

- set_fact:
    mongodb_version: "{{mongodb_version_meta[mongodb_version_options.user_input]}}"

- debug:
    msg: "mongodb_version is {{mongodb_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_VERSION=.*/APP_VERSION=v{{mongodb_version}}/g' {{installpath}}/{{appname}}/.env
