# image: https://hub.docker.com/r/jc21/nginx-proxy-manager
# docs: https://nginxproxymanager.com/guide/#quick-setup

version: "3.8"

services:
  app:
    image: websoft9dev/proxy:2.10.4
    restart: always
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "9001-9999:81"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    labels:
      com.docker.compose.w9_http.port: 80
      com.docker.compose.w9_https.port: 443
      com.docker.compose.w9_console.port: 81

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  nginx_data:
  nginx_letsencrypt: