- pause:
    prompt: |
      Choice Neo4j version: 
      0: Neo4j latest
      1: Neo4j 4.4
      2: Neo4j 4.3
      3: Neo4j 4.2
      4: Neo4j 4.1
      5: Neo4j 4.0
      6: Neo4j 5.2
      7: Neo4j 5.3 
      private: no
      Default:0
  register: neo4j_version_options

- set_fact:
    neo4j_version_meta:
      "0": "latest"
      "1": "4.4"
      "2": "4.3"
      "3": "4.2"
      "4": "4.1"
      "5": "4.0"
      "6": "5.2"
      "7": "5.3"
      
- set_fact:
    neo4j_version: "{{neo4j_version_meta[neo4j_version_options.user_input]}}"

- debug:
    msg: "neo4j_version is {{neo4j_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/DB_NEO4J_VERSION=.*/DB_NEO4J_VERSION={{neo4j_version}}/g' {{installpath}}/{{appname}}/.env
