- pause:
    prompt: |
      Choice Baota version: 
      0: Baota English version
      1: Baota Chinese version
      private: no
      Default:0
  register: baota_version_options

- set_fact:
    baota_version_meta:
      "0": "aapanel"
      "1": "btpanel"

- set_fact:
    baota_version: "{{baota_version_meta[baota_version_options.user_input]}}"

- debug:
    msg: "baota_version is {{baota_version}}"
