version: "3.8"

services:
  apphub:
    image: websoft9dev/apphub:$APPHUB_VERSION
    container_name: websoft9-apphub
    build:
      context: .
      dockerfile_inline: |
        websoft9dev/apphub:$APPHUB_VERSION
        RUN cp -r /websoft9/apphub /websoft9/src
        RUN sed -i 's/supervisorctl start apphub/supervisorctl start apphubdev/g' /entrypoint.sh
        VOLUME /websoft9/src  
    ports:
      - 9001-9999:8080
    restart: always
    volumes:
      - /data/mysource:/websoft9/src
      - apphub_media:/websoft9/media
      - apphub_logs:/websoft9/apphub/logs
    depends_on:
      - deployment
      - git
      - proxy