# Portainer can not use .env for the reason that then environments at .env may cover other stacks's .env

version: "3.8"
services:

  portainer:
    container_name: websoft9-portainer
    image: websoft9dev/portainer:2.19.0
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/init_portainer"]
    restart: unless-stopped
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9091:9000

networks:
  default:
    name: websoft9
    external: true

volumes:
  portainer: