- name: Install {{appname}}
  include_tasks: tasks/install.yml
  vars:
     app: "elk"

- name: Output elk version
  shell: |
    wget -O /tmp/containers_version.sh https://raw.githubusercontent.com/Websoft9/StackHub/main/scripts/containers_version.sh
    bash /tmp/containers_version.sh
    rm -f /tmp/containers_version.sh
