- name: wait for {{appname}} start
  wait_for:
    port: "{{nginx_reverse_proxy_port}}"
    delay: 10
    timeout: 300

- name: Check {{appname}} Version
  shell: |
    sudo echo -e "elk_version: `docker exec -it elk-elasticsearch bin/elasticsearch --version | awk -F ' ' '{print $2}'`" |sudo tee -a /data/logs/install_version.txt

- block:
    - pause:
        prompt: "Please login to Kibana UI and check it, then input Enter to continue"
        echo: no
    - name: Delete contains and images resources
      shell: |
        docker-compose down -v
        docker system prune --all --force
      args:
        chdir: /data/wwwroot/elk
  when: elk_delete_image == 'y'
