- name: Create credentials Folder
  file:
    path: /credentials
    state: directory

- name: Create credentials Folder
  file:
    path: /data/apps/{{appname}}
    state: directory

- name: Save .env
  shell : wget -N https://raw.githubusercontent.com/Websoft9/StackHub/main/apps/roles/{{appname}}/templates/.env -O /data/apps/{{appname}}/.env
