version: "3.8"

services:
  apphub:
    image: websoft9dev/apphub${APP_VERSION}
    container_name: ${APP_NAME}
    pid: host
    privileged: true
    restart: always
    volumes:
      - apphub-logs:/usr/src/app/logs
      - apphub-db:/usr/src/app/db
      - apphub-config:/usr/src/app/config
    entrypoint: bash -c "/cmd.sh"

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  apphub-logs:
  apphub-db:
  apphub-config:
