- name: Docker compose up
  shell: |
    docker compose up -d
    sleep 30
  args:
    chdir: "{{installpath}}/{{appname}}"

- name: Recursively create directory for {{appname}}
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{installpath}}/{{appname}}/data"

- name: Add softlink of all volumes for app root directory
  block:
  - name: Get volumes name
    shell: docker compose config --volumes
    register: volume_names
    args:
      chdir: "{{installpath}}/{{appname}}"
    
  - name: Create softlink of volumes
    file:
      src: "/var/lib/docker/volumes/{{appname}}_{{item}}/_data"
      dest: "{{installpath}}/{{appname}}/data/{{item}}"
      state: link
      force: yes
    loop: "{{volume_names.stdout_lines}}"

- name: Check Docker Container Service
  shell: docker ps --format "table {{.Names}}\t{{.Status}}"
  register: check_container_service
  notify: check_container_service
