- pause:
    prompt: |
      Choice Seafile version: 
      0: Seafile Community
      1: Seafile Enterprise
      private: no
      Default:0
  register: seafile_version_options

- set_fact:
    seafile_version_meta:
      "0": "seafileltd\/seafile-mc"
      "1": "docker.seafile.top\/seafileltd\/seafile-pro-mc"

- set_fact:
    seafile_version: "{{seafile_version_meta[seafile_version_options.user_input]}}"

- debug:
    msg: "seafile_version is {{seafile_version}}"

- name: Config .env for start containers
  shell: |
    sed -i 's/APP_REPO=.*/APP_REPO={{seafile_version}}/g' {{installpath}}/{{appname}}/.env
