# image: https://hub.docker.com/r/gitea/gitea
# docs: https://docs.gitea.io/zh-cn/install-with-docker
# gitea admin user create --admin --username websoft9 --random-password --email help@websoft9.com

version: '3.8'

services:
  gitea:
    container_name: $APP_NAME
    image: websoft9dev/gitea:1.20.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  gitea: