- name: Deploy Application
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Get applist
      block:
        - name: Get appname and dependencies, combine to a applist
          shell : |
            echo "{{appname}}" > /tmp/applist
            wget -N https://raw.githubusercontent.com/Websoft9/StackHub/main/apps/roles/{{appname}}/meta/main.yml   
            cat main.yml | sed -n '/dependencies/,/galaxy_info/{//!p}'|grep -|awk -F'- ' '{print $2}' >>/tmp/applist
            cat /tmp/applist
          register: applist

        - name: Check if nginx is necessary
          shell : |
            wget -N https://raw.githubusercontent.com/Websoft9/docker-{{appname}}/main/.env   
            cat .env
          register: env_content
          failed_when: False
          
        - debug:
            msg: "{{env_content.out}}"
            
        - name: App without docker register
          shell : |
            wget -N https://raw.githubusercontent.com/Websoft9/StackHub/main/apps/roles/{{appname}}/templates/.env  
            cat .env
          register: env_content
          when: env_content.stdout == ""
          
        - debug:
            msg: "show {{appnme}}"
  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: "{{appname}}", tags: "{{appname}}" }
    - { role: role_nginx, tags: "role_nginx", when: env_content.stdout.find('APP_HTTP_PORT') != -1 }
    - { role: role_init, tags: "role_init" }
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
