- name: Deploy Application
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Git Clone app docker repository
      block:
        - name: Create app directory
          shell: mkdir -p {{installpath}}
        - name: Delete {{appname}} dir for sec_installation
          shell: rm -rf {{installpath}}/{{appname}}
        - name: Clone {{appname}} in Websoft9
          git:
            repo: "https://github.com/Websoft9/docker-{{appname}}.git"
            dest: "{{installpath}}/{{appname}}"

    - name: Excute Preparation if have pre.yml
      block:
        - name: Check if pre.yml exists
          uri:
            url: https://github.com/Websoft9/StackHub/blob/main/apps/roles/{{appname}}/tasks/pre.yml
            return_content: yes
          register: pre_exists

        - name: Create app directory
          shell: pwd >> /tmp/test
        - debug: msg="{{pre_exists}}"
          
        - name: Excute pre.yml
          include_role:
            name: "{{appname}}"
            tasks_from: "pre"
          when: pre_exists.stat.exists

  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_nginx, tags: "role_nginx" }
    - { role: install, tags: "install" }
    - { role: "{{appname}}", tags: "{{appname}}" }
    - { role: role_init, tags: "role_init" }
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
