- name: Deploy Application
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
    
  pre_tasks:
    - name: Excute base roles for apps
      block:
        - name: Include base roles
          include_role:
            name: "{{item}}"
          with_items:
            - role_common
            - role_cloud

  roles:
    - { role: role_nginx, tags: "role_nginx" }
    - { role: "{{appname}}", tags: "{{appname}}" }
    - { role: role_init, tags: "role_init" }
    - { role: role_preend, tags: "preend" }
    - { role: role_end, tags: "role_end" }
