name: develop Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch origin '+refs/pull/*/merge:refs/remotes/origin/pr/*'

      - name: Checkout pull request branch
        run: git checkout refs/pull/${{ github.pr_number }}/merge

      - name: Test
        run: |
          cat README.md && cat version.json
