name: develop Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get source branch name
        id: source_branch
        run: echo "::set-output name=branch::${{ github.event.pull_request.head.ref }}"

      - name: Fetch source branch
        run: git fetch origin ${{ steps.source_branch.outputs.branch }}:${{ steps.source_branch.outputs.branch }}

      - name: Checkout source branch
        run: git checkout ${{ steps.source_branch.outputs.branch }}

      - name: Test
        run: |
          cat README.md && cat version.json
