name: develop Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      TAGS: latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Check for appmanage changes
        id: appmanage
        run: |
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          appmanage_changed=$(echo $changed_files | grep -c "appmanage")
          echo ::set-output name=changed::${appmanage_changed}

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        if: steps.appmanage.outputs.changed > 0
        with:
          image: websoft9dev/appmanage
          tags: 0.7.2
          registry: docker.io
          dockerfile: appmanage/Dockerfile
          directory: appmanage
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: add readme file
        if: steps.appmanage.outputs.changed > 0
        run: |
          cd appmanage
          touch myread.md
          echo "This repository is the easiest appmanage deployment on GitHub and DockerHub  "' 
          ```  
             git clone https://github.com/Websoft9/websoft9.git  
             sudo docker network create websoft9 && cd websoft9/appmanage &&  sudo docker compose up -d  
          ```' > myread.md

      - name: Docker Hub Description
        if: steps.appmanage.outputs.changed > 0
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: websoft9dev/appmanage
          readme-filepath: appmanage/myread.md

  ci-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get source branch commit
        id: source_commit
        run: echo "::set-output name=commit::${{ github.event.pull_request.head.sha }}"

      - name: Fetch source branch
        run: git fetch origin ${{ steps.source_commit.outputs.commit }}:${{ steps.source_commit.outputs.commit }}

      - name: Checkout source branch
        run: git checkout ${{ steps.source_commit.outputs.commit }}

      - name: Test
        run: |
          cat README.md && cat version.json
