name: develop Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git repository
        run: git init

      - name: Add remote repository
        run: git remote add origin https://github.com/${{ github.actor }}/${{ github.repository }}.git

      - name: Get pull request number
        id: pr
        run: echo "::set-output name=number::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)"

      - name: Fetch pull request branch
        run: git fetch origin pull/${{ steps.pr.outputs.number }}/merge

      - name: Checkout pull request branch
        run: git checkout FETCH_HEAD

      - name: Test
        run: |
          cat README.md && cat version.json
