name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: |
          wget https://websoft9.github.io/websoft9/install/install.sh && bash install.sh online
