name: Push to main branch

on:
  push:
    branches:
      - mains

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install appstore
        run: |
          cd install && bash install.sh

      - name: Test appmanage API
        run: |
          echo "Start to test appmanage API"
