name: upload_artifact

on:
  workflow_dispatch:
  push:
    branches: [main-no]
    paths:
      - "version.json"

jobs:
  upload_artifact:
    name: Bupload_artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Read Plugin Version
        id: update_data
        run: |
          version=$(jq -r '.VERSION' version.json)
          echo version=$version
          echo "VERSION=$version" >> $GITHUB_ENV
          changelog=$(cat changelog_latest.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT 
          echo "$changelog" >> $GITHUB_OUTPUT 
          echo "EOF" >> $GITHUB_OUTPUT

          mkdir websoft9 artifacts
          cp -r docker websoft9
          cp -r cockpit websoft9
          cp -r scripts websoft9
          cp -r install websoft9
          cp -r docs websoft9
          cp *.md websoft9
          cp version.json websoft9
          zip -r websoft9-$version.zip websoft9
          cp websoft9-$version.zip artifacts
          cp install/install.sh artifacts
          cp install/update.sh artifacts
          cp version.json artifacts
          cp CHANGELOG.md artifacts
          cp artifacts/websoft9-$version.zip artifacts/websoft9-latest.zip

      - name: Upload To Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
          container_name: release
          source_folder: artifacts/
          destination_folder: ./websoft9
          delete_if_exists: true
          fail_if_source_empty: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: /*
          tag_name: v${{ env.VERSION }}
          title: Release-v${{ env.VERSION }}
          body: ${{ steps.update_data.outputs.CHANGELOG }}
          draft: false
          prerelease: false

      # - name: Commit and push changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Push to github main
